[General]
TcpServerPort=5760
ReportStats=false
DebugLogLevel = debug

#[UdpEndpoint default]
#Mode=Server
#Address=0.0.0.0
#Port=14550

[UdpEndpoint uav1]
Mode=Server
Address=0.0.0.0
Port=14551

[UdpEndpoint uav2]
Mode=Server
Address=0.0.0.0
Port=14552

[UdpEndpoint uav3]
Mode=Server
Address=0.0.0.0
Port=14553

[UdpEndpoint uav4]
Mode=Server
Address=0.0.0.0
Port=14554

[UdpEndpoint f11]
Mode=Server
Address=0.0.0.0
Port=2000

[UdpEndpoint qgc]
Mode=Normal
Address=127.0.0.1
Port=14401

[UdpEndpoint mavros1]
Mode=Normal
Address=127.0.0.1
Port=14402
AllowSrcSysIn=1,255

[UdpEndpoint mavros2]
Mode=Normal
Address=127.0.0.2
Port=14402
AllowSrcSysIn=2,255

[UdpEndpoint mavros3]
Mode=Normal
Address=127.0.0.3
Port=14402
AllowSrcSysIn=3,255

[UdpEndpoint mavros4]
Mode=Normal
Address=127.0.0.4
Port=14402
AllowSrcSysIn=4,255
